import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import ts from 'typescript';import {readFileSync} from 'node:fs';import gate from '../src/capability-gate.js';
const source=readFileSync(new URL('../src/server.ts',import.meta.url),'utf8');const parsed=ts.createSourceFile('server.ts',source,ts.ScriptTarget.Latest,true);
const functions=['controlCatalog','executeCommandCore'];const code=ts.transpileModule(parsed.statements.filter(n=>ts.isFunctionDeclaration(n)&&functions.includes(n.name?.text)).map(n=>n.getText(parsed)).join('\n'),{compilerOptions:{target:ts.ScriptTarget.ES2022}}).outputText;
function fixture(os){const profile={os,osPretty:os,deviceClass:os==='linux'?'server':'workstation'};let nativeCalls=0;
 const context=vm.createContext({getPlatformProfile:()=>profile,loadConfig:()=>({enabledTools:{}}),readBridgeSettings:()=>({}),desktopAvailability:gate.desktopAvailability,desktopCapabilityRefusal:(type,action)=>gate.unsupportedDesktopCommand(type,action,profile),TOOL_META:['browser_snapshot','desktop_snapshot','page_to_screen','bridge_control_run'].map(name=>({name,defaultEnabled:true})),TOOL_PERMISSION_REQUIREMENTS:{},TOOL_FAMILY:{},hasBridgePermission:()=>true,getControlLimits:()=>({}),PORT:3006,enforceCommandPolicy:()=>null,controlServices:{observe:()=>{nativeCalls++;return {success:true}}}});vm.runInContext(code,context);return {context,nativeCalls:()=>nativeCalls}}
for(const os of ['macos','linux']){
 test(`${os} catalog reports native limits and still advertises browser control`,()=>{const {context}=fixture(os);const result=context.controlCatalog();assert.equal(result.surfaces.desktop.available,false);assert.equal(result.surfaces.desktop.semanticWindowControl,false);assert.equal(result.surfaces.browser.supported,true);for(const name of ['desktop_snapshot','page_to_screen'])assert.equal(result.tools.find(t=>t.name===name).localMcpAvailable,false);assert.equal(result.tools.find(t=>t.name==='browser_snapshot').localMcpAvailable,true)});
 test(`${os} shared native workflows refuse before touching Windows helpers`,async()=>{const h=fixture(os);for(const type of ['control_observe','control_run','control_activate']){const result=await h.context.executeCommandCore({type,target:{surface:'desktop',windowHandle:123}});assert.equal(result.code,'capability_unsupported')}assert.equal(h.nativeCalls(),0)});
}
test('Windows catalog and native observe retain full support',async()=>{const h=fixture('windows');assert.equal(h.context.controlCatalog().surfaces.desktop.semanticWindowControl,true);assert.equal((await h.context.executeCommandCore({type:'control_observe',target:{surface:'desktop',windowHandle:123}})).success,true);assert.equal(h.nativeCalls(),1)});
