import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../src/server.ts',import.meta.url),'utf8');const start=source.indexOf("  var saveBtn = $('providerModalSave');");const code=source.slice(start,source.indexOf('// ────── Boot',start));
function fixture(){const nodes=new Map(),timers=new Map();let requests=0,finish,closed=0;const get=id=>{if(!nodes.has(id))nodes.set(id,{value:'',checked:false,disabled:false,textContent:'',addEventListener(type,fn){this[type]=fn}});return nodes.get(id)};
 for(const [id,value] of Object.entries({providerModalName:'Fixture',providerModalUrl:'http://localhost:8000/v1',providerModalKind:'chat',providerModalConcurrency:'1'}))get(id).value=value;
 const context=vm.createContext({$:get,providerSaveBusy:false,providerModalEpoch:1,AbortController,markLocalMutate(){},loadCliState:async()=>{},closeProviderModal(){closed++},setStatus(id,text){get(id).textContent=text},API:'',setTimeout(fn){const id=timers.size+1;timers.set(id,fn);return id},clearTimeout:id=>timers.delete(id),fetch:(_url,{signal})=>{requests++;return new Promise((resolve,reject)=>{finish=body=>resolve({ok:true,json:async()=>body});signal.addEventListener('abort',()=>reject(Object.assign(Error('aborted'),{name:'AbortError'})))})}});vm.runInContext(code,context);
 return {get,context,requests:()=>requests,finish:body=>finish(body),closed:()=>closed,timeout(){for(const fn of timers.values())fn()}};
}
test('provider save prevents duplicate submission and restores the button after completion',async()=>{const h=fixture();const pending=h.get('providerModalSave').click();await h.get('providerModalSave').click();assert.equal(h.requests(),1);assert.equal(h.get('providerModalSave').disabled,true);h.finish({ok:true,provider:{name:'Fixture',available:true,models:['local']}});await pending;assert.equal(h.closed(),1);assert.equal(h.get('providerModalSave').disabled,false)});
test('completion for a closed/reopened provider dialog does not close the new dialog',async()=>{const h=fixture();const pending=h.get('providerModalSave').click();h.context.providerModalEpoch=3;h.finish({ok:true,provider:{available:true,models:['local']}});await pending;assert.equal(h.closed(),0);assert.equal(h.get('providerModalSave').disabled,false)});
test('a stalled setup unlocks with an explicit rescan recovery instead of ambiguous success',async()=>{const h=fixture();const pending=h.get('providerModalSave').click();h.timeout();await pending;assert.equal(h.closed(),0);assert.equal(h.get('providerModalSave').disabled,false);assert.match(h.get('providerModalStatus').textContent,/Re-scan before adding/)});
