'use strict';
function controlPanelHtml(nonce) {
  return `<style>
  #bridge-control-panel{position:fixed;right:18px;bottom:18px;z-index:10000;background:#14201b;color:#f2faf4;border:1px solid #476353;border-radius:12px;padding:12px 14px;max-width:420px;box-shadow:0 6px 24px #0003;font:13px/1.4 system-ui}
  #bridge-control-panel strong{display:block;font-size:14px}#bridge-control-panel .actions{display:flex;gap:8px;margin-top:9px;flex-wrap:wrap}
  #bridge-control-panel button,#bridge-report button{font:inherit;border:1px solid #a5b9aa;border-radius:6px;padding:7px 11px;cursor:pointer;background:#eff7f1;color:#14201b}
  #bridge-control-panel button:focus-visible,#bridge-report button:focus-visible{outline:3px solid #5bdf92;outline-offset:2px}
  #bridge-control-panel[data-paused="true"]{background:#342710;border-color:#edb44b;color:#fff0cf}
  #bridge-control-panel[data-paused="true"] #bridge-control-pause{background:#ffd178;border-color:#ffd178;color:#332305}
  #bridge-control-panel button:disabled{opacity:.65;cursor:wait}
  #bridge-control-panel[data-online="false"]{border-style:dashed}
  #bridge-report{box-sizing:border-box;max-width:720px;width:calc(100vw - 32px);max-height:80vh;overflow:auto;border:1px solid #8da293;border-radius:12px;padding:20px;color:#15251a;background:#f8fcf9}
  #bridge-report::backdrop{background:#0007}#bridge-report pre{max-height:40vh;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;background:#e9f0eb;padding:12px}#bridge-report h2{margin-top:0}
  @media(max-width:600px){#bridge-control-panel{left:10px;right:10px;bottom:10px;max-width:none}}
  </style>
  <section id="bridge-control-panel" aria-label="Agent control" data-online="false"><strong id="bridge-control-owner">Bridge control</strong><span id="bridge-control-state" role="status">Reading current state…</span><div class="actions"><button id="bridge-control-pause" aria-describedby="bridge-control-state" disabled>Reading control state…</button><button id="bridge-control-report">Report a problem</button></div></section>
  <dialog id="bridge-report"><h2>Review problem report</h2><p>The report stays on this computer until you share the downloaded file. Entered text, scripts and embedded images are removed from action history.</p><label><input type="checkbox" id="bridge-report-image"> Include a current image of the last controlled native window (may contain private information)</label><p id="bridge-report-status" role="status"></p><img id="bridge-report-picture" alt="Window image included in this report" hidden style="max-width:100%;max-height:240px;object-fit:contain"><pre id="bridge-report-preview"></pre><button id="bridge-report-refresh">Refresh preview</button> <button id="bridge-report-download">Download report</button> <button id="bridge-report-close">Close</button></dialog>
  <script>(()=>{
    const nonce=${JSON.stringify(nonce)}, el=id=>document.getElementById(id);let paused=false,report=null,previewId=0,known=false,pending=false,polling=false,stateVersion=0;
    const api=async(path,method='GET')=>{const r=await fetch(path,{method,headers:{'X-Empir3-Nonce':nonce}});const data=await r.json();if(!r.ok||data.success===false)throw Error(data.error||'Request failed');return data};
    function paintControl(s){if(typeof s.paused!=='boolean')throw Error('Bridge did not confirm the pause state');paused=s.paused;known=true;el('bridge-control-panel').dataset.paused=String(paused);el('bridge-control-panel').dataset.online='true';const owner=['http','direct','mcp','empir3','local-ui'].includes(s.owner)?'Connected agent':s.owner;el('bridge-control-owner').textContent=owner?(owner+' · '+(s.target?.surface==='browser'?'Browser':s.target?.surface==='desktop'?'Desktop':'Bridge')):'Bridge control';el('bridge-control-state').textContent=paused?'Paused — your permissions are preserved':s.busy?((s.phase==='waiting'?'Waiting for result':s.action||'Working')):s.message||'Idle — ready for your next request';el('bridge-control-pause').textContent=paused?'Resume control':'Pause control';el('bridge-control-pause').disabled=pending;}
    function unavailable(e){known=false;el('bridge-control-panel').dataset.online='false';el('bridge-control-state').textContent='Cannot confirm control state: '+e.message;el('bridge-control-pause').textContent='Checking control state…';el('bridge-control-pause').disabled=true;}
    async function refresh(){if(pending||polling)return;polling=true;const version=stateVersion;try{const s=await api('/api/control/status');if(version===stateVersion)paintControl(s)}catch(e){if(version===stateVersion)unavailable(e)}finally{polling=false}}
    el('bridge-control-pause').onclick=async()=>{if(pending||!known)return;pending=true;stateVersion++;el('bridge-control-panel').setAttribute('aria-busy','true');el('bridge-control-pause').disabled=true;el('bridge-control-pause').textContent=paused?'Resuming…':'Pausing…';try{paintControl(await api('/api/control/'+(paused?'resume':'pause'),'POST'))}catch(e){unavailable(e)}finally{pending=false;el('bridge-control-panel').setAttribute('aria-busy','false');el('bridge-control-pause').disabled=!known}};
    async function preview(){const id=++previewId;el('bridge-report-download').disabled=true;el('bridge-report-picture').hidden=true;report=null;el('bridge-report-status').textContent='Preparing local report…';try{const next=await api('/api/control/report'+(el('bridge-report-image').checked?'?image=1':''),'POST');if(id!==previewId)return;report=next;const view=JSON.parse(JSON.stringify(report));if(view.image?.base64){el('bridge-report-picture').src='data:'+view.image.mimeType+';base64,'+view.image.base64;el('bridge-report-picture').hidden=false;view.image.base64='[image included in download]'}el('bridge-report-preview').textContent=JSON.stringify(view,null,2);el('bridge-report-status').textContent='Review the details before sharing.';el('bridge-report-download').disabled=false}catch(e){if(id!==previewId)return;el('bridge-report-preview').textContent='';el('bridge-report-status').textContent=e.message}}
    el('bridge-control-report').onclick=()=>{el('bridge-report').showModal();preview()};el('bridge-report-refresh').onclick=preview;el('bridge-report-image').onchange=preview;el('bridge-report-close').onclick=()=>el('bridge-report').close();
    el('bridge-report-download').onclick=()=>{if(!report)return;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));a.href=url;a.download='empir3-control-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
    refresh();setInterval(refresh,1000);
  })()</script>`;
}
module.exports={controlPanelHtml};
